CREATE DATABASE orders_db;
CREATE USER melwan WITH ENCRYPTED PASSWORD 'melwan123';
GRANT ALL PRIVILEGES ON DATABASE orders_db TO melwan;


CREATE DATABASE vp_dashboard_db;
CREATE USER melwan WITH ENCRYPTED PASSWORD 'melwan123';
GRANT ALL PRIVILEGES ON DATABASE vp_dashboard_db TO melwan;